POST http://localhost:3000/register/
Content-Type : application/json

{
  "username": "adam_richard",
  "password": "richard_567",
  "name": "Adam Richard",
  "gender": "male"
}

// /login/ API 2
###
POST http://localhost:3000/login/
Content-Type : application/json

{
  "username":"JoeBiden",
  "password":"biden@123"
}

// /user/tweets/feed/ API 3
###
GET http://localhost:3000/user/tweets/feed/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNjc4MTk4MjEwfQ.f9lnzVKW1KE8pP0oOpKgbgU2mD7eq53dzecDmcE0cLc



// /user/following/ API 4
###
GET http://localhost:3000/user/following/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNjc4MTYyMDA4fQ.BFiQ-3MeuAqZoltrjLBGvT2N26tevpJ4xkv3v9QEkr4

// /user/followers/ API 5
###
GET http://localhost:3000/user/followers/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNjc4MTYyMDA4fQ.BFiQ-3MeuAqZoltrjLBGvT2N26tevpJ4xkv3v9QEkr4


// /tweets/:tweetId/ API 6
###
GET http://localhost:3000/tweets/2/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNjc4MTcyMTQ1fQ.JMIiOBR8ijjOwff4ANFbY17F2BCIXAik98zVe-c3-kw

// /tweets/:tweetId/likes/ API 7
###
GET http://localhost:3000/tweets/1/likes/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNjc4MTkwNzI1fQ.ZVPRA1E87s-2xuBOfAPdTn3lLVSWEvbbHSxYhkofR7w


// /tweets/:tweetId/replies/ API 8
###
GET http://localhost:3000/tweets/2/replies/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNjc4MTkwNzI1fQ.ZVPRA1E87s-2xuBOfAPdTn3lLVSWEvbbHSxYhkofR7w

// /user/tweets/ API 9
###
GET http://localhost:3000/user/tweets/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNjc4MTkyNzU4fQ.ffq3OaC3kL-P1BpYXNaqjJfcOmxhlrdnfjOEZjLuG_o

// /user/tweets/ API 10
###
POST http://localhost:3000/user/tweets/
Authorization: Bearer 

// /tweets/:tweetId/ API 11
###
DELETE http://localhost:3000/tweets/1/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNjc4MTk2NDk4fQ.id58v_cO5ixOQvgEDS9bVVLReDCiyG4waRVKRiTTd1I

